name: Workflow avec déclenchement par changement dans un dossier

on:
  push:
    paths:
      - 'Exercice/*'  # Spécifiez le chemin du dossier à surveiller
  pull_request:
    paths:
      - 'Exercice/*'  # Spécifiez le chemin du dossier à surveiller

jobs:
  mon_job:
    name: Mon Job
    runs-on: windows-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
