name: Check Deployment Status and Trigger Rollback

on:
  workflow_run:
    workflows: [deploy-docker]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }} # Vérification si le workflow déclencheur a échoué
    steps:
      - name: Fail
        run: echo 'The triggering workflow failed' 

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Redéployer la version précédente
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
          docker tag my-docker-image:${{ env.PREVIOUS_VERSION }} ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest


