name: Check Deployment Status and Trigger Rollback

on:
  workflow_run:
    workflows: [Q2.yml]
    types:
      - completed



jobs:
  check-deployment:
    runs-on: ubuntu-latest
    outputs:
      deployment-status: ${{ steps.get_status.outputs.status }} # Correction du nom de la sortie
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print API Response
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/Q2.yml/runs")
          echo "$response"

      - name: Get Last Deployment Status
        id: get_status
        run: |
          status=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=push&per_page=1" | jq -r '.workflow_runs[0].conclusion')
          echo "::set-output name=status::$status"

  rollback:
    needs: check-deployment
    runs-on: ubuntu-latest
    if: ${{ needs.check-deployment.outputs.deployment-status == 'failure' }} # Vérification du statut du déploiement
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Redéployer la version précédente
        run: |
          docker pull my-docker-image:${{ env.PREVIOUS_VERSION }}
          docker tag my-docker-image:${{ env.PREVIOUS_VERSION }} ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
