name: Check Deployment Status and Trigger Rollback

on:
  workflow_run:
    workflows: [Q2.yml]
    types: [completed]
    
jobs:
runs-on: ubuntu-latest
    
    steps:
      - name: Fail
        run: echo 'The triggering workflow failed' 
