name: Check Deployment Status and Trigger Rollback

on:
  workflow_run:
    workflows: ["Q2.yml"]
    types:
      - completed

jobs:
  check-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: echo 'The triggering workflow failed'
